spring.application.name=cashcard

# Enable the H2 console
spring.h2.console.enabled=true
# Set a custom path for the H2 console (optional, default is /h2-console)
spring.h2.console.path=/h2-console
# Specify the JDBC URL for an in-memory database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password


